include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - avoid_empty_else
    - avoid_unnecessary_containers
    - avoid_web_libraries_in_flutter
    - avoid_renaming_method_parameters
    - avoid_returning_null_for_void
    - empty_catches
    - empty_constructor_bodies
    - no_duplicate_case_values
    - no_logic_in_create_state
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - sized_box_for_whitespace
    - use_key_in_widget_constructors
    - void_checks
