name: kelime_hazinem
description: Kelime Hazinem
publish_to: 'none'


version: 1.2.2

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Widget packages
  flutter_svg: ^2.0.7
  flutter_layout_grid: ^2.0.3
  flutter_slidable: ^3.0.0
  pie_chart: ^5.3.2

  # Data management packages
  path: ^1.8.3
  path_provider: ^2.0.15
  sqflite: ^2.2.8+4
  shared_preferences: ^2.1.2
  flutter_riverpod: ^2.3.6
  
  # Firebase packages
  firebase_core: ^2.24.0
  cloud_firestore: ^4.13.3
  firebase_storage: ^11.5.3
  firebase_analytics: ^10.7.2
  google_mobile_ads: ^4.0.0
  
  # Other utility packages
  url_launcher: ^6.1.12
  file_picker: ^6.1.1
  cr_file_saver: ^0.0.2+1
  package_info_plus: ^5.0.1
  awesome_notifications: 0.7.4+1
  observe_internet_connectivity: ^1.0.2
  disable_battery_optimization: ^1.1.0+1
  social_share: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.3.2

flutter_native_splash:
  color: "#007AFF"
  color_dark: "#007AFF"
  android_12:
    color: "#007AFF"
    color_dark: "#007AFF"
    icon_background_color: "#A0A080"
    icon_background_color_dark: "#606060"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - fonts/OFL.txt

  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope-Regular.ttf
          weight: 400
        - asset: fonts/Manrope-Medium.ttf
          weight: 500
        - asset: fonts/Manrope-SemiBold.ttf
          weight: 600
