name: kelime_hazinem
description: Kelime Hazinem
publish_to: 'none'


version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.7
  flutter_layout_grid: ^2.0.3
  shared_preferences: ^2.1.2
  sqflite: ^2.2.8+4
  path: ^1.8.3
  path_provider: ^2.0.15
  flutter_riverpod: ^2.3.6
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3
  firebase_storage: ^11.2.5
  cr_file_saver: ^0.0.2+1
  awesome_notifications: ^0.7.4+1
  flutter_slidable: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - android/app/src/main/res/drawable/

  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope-ExtraLight.ttf
          weight: 200
        - asset: fonts/Manrope-Light.ttf
          weight: 300
        - asset: fonts/Manrope-Regular.ttf
          weight: 400
        - asset: fonts/Manrope-Medium.ttf
          weight: 500
        - asset: fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: fonts/Manrope-Bold.ttf
          weight: 700
        - asset: fonts/Manrope-ExtraBold.ttf
          weight: 800
