name: kelime_hazinem
description: Kelime Hazinem
publish_to: 'none'


version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.7
  flutter_layout_grid: ^2.0.3
  shared_preferences: ^2.1.2
  sqflite: ^2.2.8+4
  path: ^1.8.3
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/